#!/bin/bash

# function c
c() {
	 file_name="$1"

	if [ -f "$file_name" ]; then
		contents=$(cat $file_name)
	else
		echo "File not found: $file_name"
	fi

	while IFS= read -r -n 1 _; do
		((cnt++))
	done < "$file_name"

	echo "  $cnt $file_name"
}

#function l 
l() {
	file_name="$1"

	if [ -f "$file_name" ]; then
		contents=$(cat $file_name)
	else
		echo "File not found: $file_name"
	fi

	line=0
	while IFS= read -r _; do
		((line++))
	done < "$file_name"
	echo "    $line $file_name"
}

while getopts ":cl:" opt; do
	case $opt in
		c)
			config_file="$OPTARG"
			if [ -z "$config_file" ]; then
				echo "Option -$opt requires a non-empty argument."
				exit 1
			fi
			c $2
			;;
		l)
			config_file="$OPTARG"
			if [ -z "$config_file" ]; then
				echo "Option -$opt requires a non-empty argument."
				exit 1
			fi
			l $2
			;;
		:)
			echo "Option -$OPTARG requires an argument."
			;;
		\?)
			echo $opt
			;;
	esac
done

# Shift to remove processed options, if needed
shift $((OPTIND-1))



